const express = require("express");
const uTurnApp = express();
const bodyParser = require("body-parser");
const usersRoute = require("../routes/users.routes");
const profilesRoute = require("../routes/profile.routes");
const currenciesRoute = require("../routes/currency.routes");
const transactionsRoute = require("../routes/transactions.routes");
const customersRoute = require("../routes/customers.routes");
const officeAccountsRoute = require("../routes/office_accounts.routes");
const remindersRoute = require("../routes/reminders.routes");
uTurnApp.use(bodyParser.json());
uTurnApp.use("/api/v1/users", usersRoute);
uTurnApp.use("/api/v1/profiles", profilesRoute);
uTurnApp.use("/api/v1/currencies", currenciesRoute);
uTurnApp.use("/api/v1/transactions", transactionsRoute);
uTurnApp.use("/api/v1/customers", customersRoute);
uTurnApp.use("/api/v1/officeAccounts", officeAccountsRoute);
uTurnApp.use("/api/v1/reminders", remindersRoute);
module.exports = uTurnApp;
